
// eslint-disable-next-line import/order
import { Jost } from "next/font/google"

import "../assets/styles/globals.css"

import { Metadata } from "next/types";
import { Session } from "next-auth"
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import FooterFeatures from "@/components/blocks/FooterFeatures";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header"
import Providers from "@/components/layout/Providers"

const jost = Jost({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Next-Ecommerce",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session: Session | null;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Providers session={session}>
          <Header />
          <main className="min-h-screen">
            {children}
          </main>
          <FooterFeatures />
          <Footer />
        </Providers>
        <ToastContainer
          position="bottom-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        // transition: "Slide"
        />
      </body>
    </html>
  )
}
